version: '3.8'

services:
  redis:
    image: redis:7
    container_name: elmeet-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - elmeet-network
    restart: unless-stopped

  ws-backend:
    image: iamdeepakpatankar/elmeet-ws-backend:${IMAGE_TAG}
    container_name: elmeet-ws-backend
    pull_policy: always
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - FRONTEND_URL=${FRONTEND_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_PASSWORD=${JWT_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
    networks:
      - elmeet-network
    restart: unless-stopped

networks:
  elmeet-network:
    driver: bridge